### ISSUE TITLE
Error during initialization on Windows 8.1 Pro via Boot Camp with .NET 4.6.1

### ISSUE THREAD

**Issue by logiclrd** [6A/Ryder#4]
A co-worker of mine is trying to run an app that is using Ryder to override internal implementation details of WPF's `TreeView` class. This application works fine on a number of other systems, but on this particular system, it encounters the following error during initialization:
```
Exception Info: System.IO.FileNotFoundException
  at Ryder.Helpers.AllowRW(IntPtr)
  at Ryder.MethodRedirection..ctor(System.Reflection.MethodBase, System.Reflection.MethodBase, Boolean)
  at Ryder.Redirection.RedirectCore(System.Reflection.MethodBase, System.Reflection.MethodBase, Boolean)
```
This workstation is a Mac running Windows 8.1 Pro via Boot Camp, if that makes any difference, and it has .NET 4.6.1 installed.

I had a go at trying to figure out what could cause the problem, but all I came up with, looking at the `Helpers.cs` code, is that `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` must be returning `false`. I created a test application to call this particular method from the `System.Runtime.InteropServices.RuntimeInformation` package, and it did not return `false` for me. I have verified that it is the same version of `System.Runtime.InteropServices.RuntimeInformation.dll` in both cases.

What can I check next?

**Comment by 6A** [comment]
I'll look into it. So if I recap: 
- There is a file IO exception in AllowRW on Windows, running itself on Boot Camp. 
- IsOSPlatform(OSPlatform.Windows)` returns `true` on the system. Also, is the system 64 or 32 bits? Unfortunately I haven't had the chance to test Ryder on the latter. 

If so, the exception could be caused when trying to load kernel32.dll for interop. Do you have more details on the exception? It is usually followed by a message.

**Comment by 6A** [comment]
I suppose we should try setting `SetLastError` to true before anything, in case there is indeed a mechanism that throws when it is not the case. Another possibility for `FileNotFoundException` to be thrown is when an assembly cannot be found, which might be the case of `System.[..].RuntimeInformation`, can you try using it at some other point in the program to see if it can be loaded?

**Comment by logiclrd** [comment]
This same application is running fine via, I'm pretty sure, the same deployment mechanism on other computers, but I will double-check that the deployment on the workstation exhibiting the problem is not damaged in some way.

**Comment by logiclrd** [comment]
This last suggestion of yours was in fact the solution to the problem. On machines where it was working without issues, it turns out that `System.Runtime.Interop.RuntimeInformation.dll` was in the GAC. Perhaps it gets installed alongside Visual Studio or somesuch? The machine having problems did not have it in the GAC -- and did not have it in the application deployment folder either. It simply had not occurred to me that the majority of our workstations might have a DLL brought in via NuGet package installed to their GAC. :-P

**Comment by logiclrd** [comment]
Thanks for your time & attention, it is appreciated :-)

**Comment by 6A** [comment]
Didn't know this could happen either, but I'm glad to see that the problem is resolved. Please come back to me with feedback and suggestions if you wish to do so!
